/// Lista de palavras ofensivas em português, inglês e espanhol
class ProfanityList {
  static Set<String> getProfanityWords() {
    return {
      // ============================
      // PORTUGUÊS
      // ============================

      // Palavrões básicos
      'puta',
      'puto',
      'putinha',
      'putinha',
      'putaria',
      'putona',
      'putona',
      'putaquepariu',
      'puta que pariu',
      'putaquepariu',
      'merda',
      'bosta',
      'porra',
      'caralho',
      'caralhinho',
      'caralhão',
      'cacete',
      'caceta',
      'cacetinho',
      'cacetonas',
      'foda',
      'fode',
      'foder',
      'fudido',
      'fudida',
      'fodido',
      'fodida',
      'fodeu',
      'fodendo',
      'fudendo',
      'fudidao',
      'fudidão',
      'fudidao',
      'fudida',
      'fudiu',
      'fudição',
      'fudiçao',
      'fudicao',

      // Região anal / traseira
      'cu',
      'cuzao',
      'cuzão',
      'cuzona',
      'cuzuda',
      'cuzudo',
      'fiofó',
      'fiofo',
      'anão do cu',
      'cu arrombado',
      'cuzinho',
      'cuzao',
      'cuzona',

      // Genitais & afins
      'buceta',
      'boceta',
      'bucetao',
      'bucetão',
      'bucetinha',
      'xoxota',
      'xoxotinha',
      'xereca',
      'xana',
      'xaninha',
      'perereca',
      'pererequinha',
      'piroca',
      'pirocao',
      'pirocão',
      'piroquinha',
      'pica',
      'picão',
      'picona',
      'pirocudo',
      'pau',
      'pauzao',
      'pauzão',
      'pauduro',
      'pau duro',
      'rola',
      'rolinha',
      'rolo',
      'pinto',
      'pintinho',
      'penis',
      'pênis',
      'vagina',
      'vaginão',
      'clitóris',
      'clitoris',
      'testículo',
      'testiculo',
      'saco',
      'sacudo',
      'ovário',
      'ovario',

      // Práticas sexuais
      'sexo',
      'sexual',
      'transar',
      'transando',
      'trepar',
      'trepando',
      'trepada',
      'gozar',
      'gozando',
      'gozada',
      'gozo',
      'gozador',
      'gozadeira',
      'punheta',
      'punheteiro',
      'punheteira',
      'punhetinha',
      'punhetão',
      'masturbar',
      'masturbando',
      'masturbação',
      'boquete',
      'boquetinho',
      'chupa',
      'chupar',
      'chupando',
      'chupeta' , // ambígua, mas muitas vezes sexual
      'mamar',
      'mamada',
      'mamadinha',
      'lambeção',
      'lamber',
      'lambe cu',
      'lambe-ovo',
      'anal',
      'sexo anal',
      'sexo oral',
      'oral',
      '69',
      'sessenta e nove',
      'suruba',
      'orgia',
      'orgias',

      // Prostituição / promiscuidade
      'safado',
      'safada',
      'safadinha',
      'safadão',
      'putinha',
      'vagabundo',
      'vagabunda',
      'vagaba',
      'vagabundinha',
      'piranha',
      'piranhuda',
      'piranhona',
      'vadia',
      'vadiazinha',
      'vadiagem',
      'prostituta',
      'prostituto',
      'puteiro',
      'bordel',
      'cabaré',
      'cabare',
      'cabarézinho',
      'garota de programa',
      'garoto de programa',
      'escort',
      'meretriz',

      // Ofensas pessoais
      'babaca',
      'cretino',
      'imbecil',
      'idiota',
      'estupido',
      'estúpido',
      'burro',
      'burra',
      'jumento',
      'jegue',
      'otario',
      'otário',
      'otaria',
      'otária',
      'escroto',
      'escrota',
      'nojento',
      'nojenta',
      'desgraçado',
      'desgraçada',
      'desgraça',
      'miserável',
      'miseravel',
      'vagabundo',
      'relaxa vagabundo',
      'arrombado',
      'arrombada',
      'corno',
      'corna',
      'corninho',
      'chifrudo',
      'chifruda',
      'chifrinho',
      'trouxa',
      'trouxão',
      'otário',
      'fdp',
      'filho da puta',
      'filha da puta',
      'filhodaputa',
      'filhadaputa',
      'filhasputa',
      'cabra safado',
      'canalha',
      'mongol',
      'mongoloide',
      'mongolóide',
      'retardado',
      'retardada',
      'débil mental',
      'debilmantal',
      'animal',
      'besta',
      'imbecil',
      'inútil',
      'inutil',
      'lixo',
      'porcaria',
      'sem vergonha',
      'sem-vergonha',
      'vagabunda',
      'vagaba',

      // Ofensas ligadas a sexualidade / gênero (muitas vezes homofóbicas)
      'viado',
      'viadinho',
      'viadin',
      'bicha',
      'bichona',
      'bichinha',
      'bichona',
      'gayzinho',
      'sapatão',
      'sapatao',
      'sapatona',
      'machona',
      'traveco',
      'trava',
      'travesti',
      'boiola',
      'boiolinha',
      'frango',
      'baitola',
      'maricas',
      'frescurento',
      'frescurenta',

      // Blasfêmias / religião
      'inferno',
      'vai pro inferno',
      'vai para o inferno',
      'vai pro diabo',
      'vai pra merda',
      'vai se ferrar',
      'vai se foder',
      'vai se fuder',
      'vai se lascar',
      'vai tomar no cu',
      'vai toma no cu',
      'vai tomar no seu cu',
      'vai tomar no meio do cu',
      'vai se danar',
      'vsf',
      'vtnc',
      'tmnc',
      'toma no cu',
      'se fode',
      'se fuder',
      'se ferrar',
      'demônio',
      'demonio',
      'satanas',
      'satanás',
      'capeta',
      'diabo',

      // Drogas (muitas vezes desejado em filtro)
      'maconha',
      'cannabis',
      'erva',
      'beck',
      'baseado',
      'drogado',
      'drogada',
      'cocaína',
      'cocaina',
      'crack',
      'heroína',
      'heroina',
      'pó',
      'po',
      'lança perfume',
      'lanca perfume',
      'êxtase',
      'ecstasy',

      // ============================
      // INGLÊS
      // ============================

      // Básicos
      'fuck',
      'fucking',
      'fucked',
      'fucker',
      'motherfucker',
      'motherfuckers',
      'mf',
      'shit',
      'shitty',
      'bullshit',
      'bs',
      'bitch',
      'bitches',
      'biatch',
      'biotch',
      'bastard',
      'damn',
      'dammit',
      'hell',
      'bloody',
      'crap',
      'ass',
      'asshole',
      'arse',
      'arsehole',
      'jackass',
      'dumbass',
      'smartass',

      // Corpo / sexo
      'dick',
      'dicks',
      'dickhead',
      'dickhead',
      'dickwad',
      'dickweed',
      'cock',
      'cocksucker',
      'cockhead',
      'pussy',
      'pussies',
      'cunt',
      'cunts',
      'penis',
      'vagina',
      'boob',
      'boobs',
      'boobies',
      'tit',
      'tits',
      'titty',
      'titties',
      'balls',
      'ball sack',
      'ballsack',
      'scrotum',
      'butt',
      'butthole',
      'butthead',
      'anus',
      'anal',
      'orgasm',
      'ejaculation',
      'ejaculate',
      'cum',
      'cumming',
      'cumshot',
      'jizz',
      'spunk',

      // Práticas sexuais
      'blow job',
      'blowjob',
      'handjob',
      'hand job',
      'rimjob',
      'rim job',
      'deepthroat',
      'deep throat',
      'fellatio',
      'cunnilingus',
      'sex',
      'sexy',
      'hardcore',
      'hard core',
      'bdsm',
      'kinky',
      'porn',
      'porno',
      'pornography',
      'pornographic',
      'stripper',
      'strip club',
      'lapdance',
      'lap dance',

      // Violência sexual
      'rape',
      'raped',
      'rapist',
      'gangbang',
      'gang bang',
      'molest',
      'molester',

      // Prostituição / promiscuidade
      'whore',
      'whores',
      'slut',
      'sluts',
      'hooker',
      'hookers',
      'escort',
      'escorts',
      'prostitute',
      'prostitutes',
      'tramp',
      'skank',
      'skanky',
      'harlot',

      // Ofensas pessoais
      'retard',
      'retarded',
      'idiot',
      'idiots',
      'stupid',
      'stupids',
      'dumb',
      'dumbass',
      'moron',
      'morons',
      'imbecile',
      'loser',
      'losers',
      'jerk',
      'jerks',
      'douche',
      'douchebag',
      'douchebags',
      'prick',
      'twat',
      'twats',
      'wanker',
      'wankers',
      'tosser',
      'tosspot',
      'bastards',
      'scumbag',
      'scumbags',
      'trash',
      'garbage',
      'freak',
      'weirdo',

      // Racial / homofóbicas etc. (para filtro)
      'fag',
      'fags',
      'faggot',
      'faggots',
      'dyke',
      'dykes',
      'tranny',
      'trannies',
      'queer', // pode ser neutro em alguns contextos, mas aqui é ofensa
      'nigger',
      'niggers',
      'nigga',
      'niggas',
      'chink',
      'chinks',
      'spic',
      'spics',
      'wetback',
      'wetbacks',
      'camel jockey',
      'sand nigger',
      'sandnigger',

      // Raiva / expressão
      'piss',
      'pissed',
      'pissed off',
      'screw you',
      'screw u',
      'screw him',
      'screw her',
      'go to hell',
      'drop dead',
      'die in a fire',

      // Drogas
      'weed',
      'marijuana',
      'cannabis',
      'joint',
      'blunt',
      'stoner',
      'coke',
      'cocaine',
      'meth',
      'methamphetamine',
      'heroine',
      'heroin',
      'lsd',
      'acid',
      'shrooms',
      'ecstasy',
      'mdma',
      'opium',
      'opiate',

      // ============================
      // ESPANHOL
      // ============================

      // Básicos
      'mierda',
      'mierdita',
      'carajo',
      'carajos',
      'joder',
      'jodido',
      'jodida',
      'jodidos',
      'jodidas',
      'jodiendo',
      'jodete',
      'jódete',
      'coño',
      'cono',
      'coñazo',
      'coñito',
      'puta',
      'puto',
      'putita',
      'putita',
      'putazo',
      'putero',
      'putear',
      'puteador',
      'chingar',
      'chingado',
      'chingada',
      'chingados',
      'chingadas',
      'chingándote',
      'chingate',
      'chingate',
      'chingada madre',
      'chingada',
      'chingón',
      'chingon',
      'chingona',
      'hijo de puta',
      'hija de puta',
      'hijo\'e puta',
      'hijo de perra',
      'hija de perra',
      'malparido',
      'malparida',

      // Genitais / corpo
      'verga',
      'vergazo',
      'vergazos',
      'vergas',
      'polla',
      'pollas',
      'pene',
      'pito',
      'pitos',
      'pija',
      'pijas',
      'chota',
      'chotas',
      'choto',
      'chotos',
      'huevo',
      'huevos',
      'huevón',
      'huevon',
      'huevona',
      'huevones',
      'huevonas',
      'concha',
      'conchudo',
      'conchuda',
      'conchudos',
      'conchudas',
      'conchuda',
      'conchita',
      'chocha',
      'chocho',
      'chochos',
      'nalgas',
      'trasero',
      'culo',
      'culos',
      'culazo',
      'culera',
      'culero',
      'ojete',
      'ano',

      // Práticas sexuais
      'follar',
      'follando',
      'follada',
      'folladas',
      'coger',
      'cogiendo',
      'cogida',
      'cogidas',
      'tirar',
      'tirarse',
      'tirandose',
      'tragar semen',
      'mamada',
      'mamadita',
      'mamon',
      'mamón',
      'mamada',
      'chuparla',
      'chupar',
      'chupon',
      'chupón',
      'pajear',
      'paja',
      'pajero',
      'pajera',
      'masturbar',
      'masturbación',
      'masturbacion',
      'sexo',
      'sexual',
      'porno',
      'pornografía',
      'pornografia',
      'orgía',
      'orgia',
      'orgías',
      'orgias',

      // Prostituição / promiscuidade
      'puta barata',
      'puta asquerosa',
      'zorra',
      'zorras',
      'perra',
      'perras',
      'ramera',
      'rameras',
      'putona',
      'putona',
      'putilla',
      'prostituta',
      'prostitutas',
      'prostíbulo',
      'prostibulo',
      'burdel',
      'cabaret',
      'table dance',
      'escort',

      // Ofensas pessoais
      'pendejo',
      'pendeja',
      'pendejos',
      'pendejas',
      'cabrón',
      'cabron',
      'cabrona',
      'cabrones',
      'cabronas',
      'imbécil',
      'imbecil',
      'idiota',
      'idiotas',
      'estúpido',
      'estupido',
      'estúpida',
      'estupida',
      'retrasado',
      'retrasada',
      'retrasados',
      'retrasadas',
      'tarado',
      'tarada',
      'tarados',
      'taradas',
      'gilipollas',
      'capullo',
      'capullos',
      'pelotudo',
      'pelotuda',
      'pelotudos',
      'pelotudas',
      'boludo',
      'boluda',
      'boludos',
      'boludas',
      'boludo',
      'gil',
      'giles',
      'zopenco',
      'zopenca',
      'baboso',
      'babosa',
      'asno',
      'burro',
      'burra',

      // Ofensas ligadas a sexualidade / gênero
      'marica',
      'maricón',
      'maricon',
      'mariconazo',
      'maricona',
      'maricas',
      'putito',
      'putitos',
      'loca',
      'loca de mierda',
      'mariposón',
      'mariposa',
      'travelo',
      'travesti',
      'puto maricón',

      // Expressões e frases ofensivas
      'vete a la mierda',
      'vete al carajo',
      'vete a la chingada',
      'vete a la verga',
      'vete a tomar por culo',
      'vete a la concha de tu madre',
      'hijo de la gran puta',
      'hija de la gran puta',
      'maldito',
      'maldita',
      'malditos',
      'malditas',

      // Drogas
      'marihuana',
      'mariguana',
      'cannabis',
      'porro',
      'porros',
      'churro',
      'churros',
      'cocaína',
      'cocaina',
      'perico',
      'crack',
      'heroína',
      'heroina',
      'anfetamina',
      'metanfetamina',
      'éxtasis',
      'extasis',

    };
  }
}
